language: python

python:
  - 3.7
  - 3.6
  - 3.5
  - 2.7

cache: pip

before_install:
  - pip install coverage pyflakes

install:
  - pip install .

script:

  # Static analysis
  - pyflakes .

  # Unit tests
  - coverage run

after_success:
  # Report coverage and send to Codecov
  - coverage report
  - pip install codecov && codecov

after_script:
  - coverage report

matrix:
  fast_finish: true
