language: python

python:
  - 3.6
  - 2.7
  - 3.5
  - 3.4

cache: pip

install:
  - pip install coverage pyflakes

script:

  # Static analysis
  - pyflakes .

  # Unit tests
  - coverage run --include=twitter_search_funcs.py test_twitter_search_funcs.py

after_success:
  # Report coverage and send to Codecov
  - coverage report
  - pip install codecov && codecov

after_script:
  - coverage report

matrix:
  fast_finish: true
