language: python

python:
  - 3.7
  - 3.6
  - 3.5

cache: pip

before_install:
  - pip install coverage flake8

install:
  - pip install .

script:

  # Static analysis
  - flake8 .

  # Unit tests
  - coverage run twitter_search/tests/*

after_success:
  # Report coverage and send to Codecov
  - coverage report
  - pip install codecov && codecov

after_script:
  - coverage report

matrix:
  fast_finish: true
